script protected

diff --git a/system/02 b/system/02
--- a/system/02
+++ b/system/02
@@ -14,14 +14,27 @@
 # Log as root
 #	su
 
-# Get previous hostname
-	PHNAME=$(hostname)
-
 # Set hostname (sysitem) name variable
 	HNAME="Antoine"
 
+# Get previous hostname
+	if ! PHNAME=$(hostname 2>/dev/null); then
+		echo "\033[31mCould not find hostname\033[0m"
+		exit
+	fi
+
 # Change hostname (temp)
-	hostname $HNAME
+	if ! hostname $HNAME 2>/dev/null ; then
+		echo "\033[31mCould not change hostname\033[0m"
+		exit
+	else
+		echo "\033[92mHostname \033[0m$PHNAME\033[92m changed to \033[0m$(hostname)"
+	fi
 
 # Change hostname (hostnamectl) (perm)
-#	hostnamectl set-hostname $HNAME 2> bin
+#	if ! hostnamectl set-hostname $HNAME 2>/dev/null ; then
+#		echo "\033[31mCould not change hostname\033[0m"
+#		exit
+#	else
+#		echo "\033[92mHostname \033[0m$PHNAME\033[92m changed to \033[0m$(hostname)"
+#	fi
diff --git a/system/03 b/system/03
--- a/system/03
+++ b/system/03
@@ -6,15 +6,15 @@
 #    By: abarthel <abarthel@student.42.fr>          +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2019/01/09 17:24:17 by abarthel          #+#    #+#              #
-#    Updated: 2019/01/10 17:20:08 by abarthel         ###   ########.fr        #
+#    Updated: 2019/01/11 12:19:34 by abarthel         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
-Edit /etc/hosts for permanent hostname change.
+#Edit /etc/hosts for permanent hostname change.
 
-Also edit, /etc/hostname.
+#Also edit, /etc/hostname.
 
-Or use,
+#Or use,
 
 	#!/bin/sh
 
@@ -25,7 +25,15 @@ Or use,
 		HNAME="New"
 	
 	# Store old hostname
-		$PH=$(hostname)
+		if ! PH=$(hostname 2>/dev/null); then
+			echo "\033[31mCould not find hostname\033[0m"
+			exit
+		fi
 
 	# Change hostname (hostnamectl) (perm)
-		hostnamectl set-hostname $HNAME
+		if hostnamectl set-hostname $HNAME 2>/dev/null; then
+			echo "$PH\033[92m hostname permanently changed to\033[0m $HNAME"
+		else
+			echo "\033[31mCould not change $PH hostname to $HNAME\033[0m"
+			exit
+		fi
